name: Deploy backend-main to Wow Server

on:
  workflow_dispatch:  # Manually trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}

      - name: Deploy backend-main on Server
        run: |
          ssh ubuntu@$SERVER_IP << 'EOF'
            set -e  # Stop execution if any command fails

            echo "Configuring Git safe directory..."
            git config --global --add safe.directory /var/www/html/wow/backend-main

            echo "Navigating to backend-main..."
            cd /var/www/html/wow/backend-main

            echo "Pulling latest code from main branch..."
            git fetch origin main
            git reset --hard origin/main
            git pull origin main

            # List of backend services inside backend-main
            services=("history-earning" "mass_notification" "payments" "server" "whatspp_messenger")

            echo "Installing dependencies for each service..."
            for service in "${services[@]}"; do
              if [ -d "$service" ]; then
                echo "Installing dependencies in $service"
                cd "$service"
                npm install --legacy-peer-deps
                cd ..
              else
                echo "Skipping $service (not found)"
              fi
            done

            echo "Building and running Docker Compose..."
            docker-compose down
            docker-compose build
            docker-compose up -d

            echo "Deployment completed successfully! 🚀"

          EOF
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
